<?php
require __DIR__.'/../vendor/autoload.php';
$app=require __DIR__.'/../bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
set_exception_handler(function(Throwable $e){fwrite(STDERR,(string)$e);exit(1);});
config(['database.default'=>'mysql','database.connections.mysql.host'=>'127.0.0.1','database.connections.mysql.port'=>3306,'database.connections.mysql.database'=>'biolync_test','database.connections.mysql.username'=>'root','database.connections.mysql.password'=>'ci-only','database.connections.mysql.strict'=>false,'cache.default'=>'array','session.driver'=>'array','linkstack.disable_random_user_ids'=>'true']);
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use App\Models\User;
use App\Models\UserData;
use App\Support\ProfileGallery;
DB::purge();
function verifyMysql($ok,$message){if(!$ok)throw new RuntimeException($message);echo "PASS MySQL: $message\n";}
Schema::create('users',function($t){$t->id();$t->string('image')->nullable();$t->string('role')->default('user');$t->string('name');$t->string('email');$t->string('password');$t->timestamps();});
$legacy=User::create(['name'=>'Legacy','email'=>'legacy@example.test','password'=>'unused','image'=>str_repeat('x',400)]);
verifyMysql(strlen(DB::table('users')->where('id',$legacy->id)->value('image'))===255,'original non-strict VARCHAR silently truncates oversized data');
$owner=User::create(['name'=>'Owner','email'=>'owner@example.test','password'=>'unused']);$owner->role='vip';$owner->save();
UserData::saveData($owner->id,'profile_header',['position'=>'top']);
$before=DB::table('users')->where('id',$owner->id)->value('image');
$migration=require __DIR__.'/../database/migrations/2026_10_03_200000_expand_profile_metadata_storage.php';$migration->up();
$type=DB::selectOne("SELECT DATA_TYPE AS kind FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'image'")->kind;
verifyMysql($type==='longtext' && DB::table('users')->where('id',$owner->id)->value('image')===$before,'migration widens storage and preserves existing data');
Auth::login($owner);
$c=new App\Http\Controllers\UserController;
$c->profileHeader(Request::create('/studio/profile-header','POST',['header_position'=>'top'],[],['header_media'=>UploadedFile::fake()->image('header.jpg',1200,440)]));
$header=UserData::getData($owner->id,'profile_header');
$uploads=[];for($i=0;$i<12;$i++)$uploads[]=UploadedFile::fake()->image('gallery.jpg',100,160);
$g=new App\Http\Controllers\ProfileGalleryController;
$g->save(Request::create('/studio/photo-gallery','POST',['enabled'=>1],[],['photos'=>$uploads]));
$gallery=ProfileGallery::get($owner->id);
$captions=[];foreach($gallery['photos'] as $photo)$captions[$photo['id']]=str_repeat('A',200);
$g->save(Request::create('/studio/photo-gallery','POST',['enabled'=>1,'captions'=>$captions]));
UserData::saveData($owner->id,'links-new-tab',true);
$raw=DB::table('users')->where('id',$owner->id)->value('image');
$decoded=json_decode($raw,true,512,JSON_THROW_ON_ERROR);
verifyMysql(strlen($raw)>255 && count($decoded['photo_gallery']['photos'])===12 && strlen($decoded['photo_gallery']['photos'][0]['caption'])===200,'full gallery and captions survive real MySQL writes');
verifyMysql($decoded['profile_header']['media']===$header['media'] && is_file(base_path($header['media'])),'header metadata and file survive gallery and settings saves');
verifyMysql(str_contains(view('linkstack.elements.photo-gallery',['userinfo'=>$owner])->render(),'biolync-gallery-columns') && str_contains(view('linkstack.elements.profile-header',['userinfo'=>$owner])->render(),$header['media']),'both media sections render after database round trip');
$migration->down();
verifyMysql(DB::table('users')->where('id',$owner->id)->value('image')===$raw,'rollback retains wide storage and saved media');
